compliance: checkov

diff --git a/.github/workflows/checkov.yml b/.github/workflows/checkov.yml
--- a/.github/workflows/checkov.yml
+++ b/.github/workflows/checkov.yml
@@ -26,129 +26,19 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v4
 
-      - name: Checkov GitHub Action
-        uses: bridgecrewio/checkov-action@v12.1347.0
-        with:
-          directory: ${{ env.TF_WORKING_DIR }}
-          soft_fail: true
-          framework: terraform
-          # download_external_modules: true
-
-      - name: Upload SARIF file
-        uses: github/codeql-action/upload-sarif@v3
-        
-        # Results are generated only on a success or failure
-        # this is required since GitHub by default won't run the next step
-        # when the previous one has failed. Security checks that do not pass will 'fail'.
-        # An alternative is to add `continue-on-error: true` to the previous step
-        # Or 'soft_fail: true' to checkov.
-        if: success() || failure()
-        with:
-          sarif_file: results.sarif
-
-      # - name: Save SARIF File as Artifact
-      #   if: success()
-      #   run: |
-      #     python convert_to_sarif.py ${{ steps.checkov_scan.outputs.checkov_results }} checkov_results.sarif
-      #     echo "SARIF_FILE_URL=$(realpath checkov_results.sarif)" >> $GITHUB_ENV
-
-      
-      # - name: Display Checkov Results
-      #   if: success()
-      #   run: |
-      #     echo "Checkov Scan Results:"
-      #     cat ${{ steps.checkov_scan.outputs.checkov_results }}
+      - name: Install Checkov
+        run: pip install checkov
+   
       
       
-      
-      - name: Publish Checkov Plan to Task Summary
-        env:
-          SUMMARY: ${{ steps.checkov_scan.outputs.checkov_results }}
-        run: echo "$SUMMARY" >> $GITHUB_STEP_SUMMARY
-      
-      # - name: Publish Checkov Results to Task Summary
-      #   if: success()
-      #   run: |
-      #     echo "SUMMARY=$(cat ${{ steps.checkov_scan.outputs.checkov_results }})" >> $GITHUB_ENV
-      
-      
-      # - name: Upload SARIF File
-      #   if: success()
-      #   uses: actions/upload-artifact@v4
-      #   with:
-      #     name: results.sarif #checkov-sarif-results
-      #     path: ${{ steps.checkov_scan.outputs.checkov_results }} #. #checkov_results.sarif
-      #     # overwrite: false
+        # - name: Checkov GitHub Action
+        # uses: bridgecrewio/checkov-action@v12.1347.0
+        # with:
+        #   directory: ${{ env.TF_WORKING_DIR }}
+        #   soft_fail: true
+        #   framework: terraform
+        #   # download_external_modules: true
 
-      # - name: Save SARIF File as Artifact
-      #   if: success()
-      #   uses: actions/upload-artifact@v2
-      #   with:
-      #     name: checkov-sarif-results
-      #     path: checkov_results.sarif
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-# name: checkov
-
-# # Controls when the workflow will run
-# on:
-#   # Triggers the workflow on push or pull request events but only for the "main" branch
-#   # push:
-#   #   branches: [ "main", "master" ]
-#   # pull_request:
-#   #   branches: [ "main", "master" ]
-
-#   # Allows you to run this workflow manually from the Actions tab
-#   workflow_dispatch:
-
-# # A workflow run is made up of one or more jobs that can run sequentially or in parallel
-# jobs:
-#   # This workflow contains a single job called "scan"
-#   scan:
-#     permissions:
-#       contents: read # for actions/checkout to fetch code
-#       security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
-#       actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
-      
-#     # The type of runner that the job will run on
-#     runs-on: ubuntu-latest
-
-#     # Steps represent a sequence of tasks that will be executed as part of the job
-#     steps:
-#       # Checks-out your repository under $GITHUB_WORKSPACE, so follow-up steps can access it
-#       - uses: actions/checkout@v4
-
-#       - name: Checkov GitHub Action
-#         uses: bridgecrewio/checkov-action@v12
-#         with:
-#           # This will add both a CLI output to the console and create a results.sarif file
-#           output_format: cli,sarif
-#           output_file_path: console,results.sarif
-        
 #       - name: Upload SARIF file
 #         uses: github/codeql-action/upload-sarif@v3
         
@@ -160,3 +50,118 @@ jobs:
 #         if: success() || failure()
 #         with:
 #           sarif_file: results.sarif
+
+#       # - name: Save SARIF File as Artifact
+#       #   if: success()
+#       #   run: |
+#       #     python convert_to_sarif.py ${{ steps.checkov_scan.outputs.checkov_results }} checkov_results.sarif
+#       #     echo "SARIF_FILE_URL=$(realpath checkov_results.sarif)" >> $GITHUB_ENV
+
+      
+#       # - name: Display Checkov Results
+#       #   if: success()
+#       #   run: |
+#       #     echo "Checkov Scan Results:"
+#       #     cat ${{ steps.checkov_scan.outputs.checkov_results }}
+      
+      
+      
+#       - name: Publish Checkov Plan to Task Summary
+#         env:
+#           SUMMARY: ${{ steps.checkov_scan.outputs.checkov_results }}
+#         run: echo "$SUMMARY" >> $GITHUB_STEP_SUMMARY
+      
+#       # - name: Publish Checkov Results to Task Summary
+#       #   if: success()
+#       #   run: |
+#       #     echo "SUMMARY=$(cat ${{ steps.checkov_scan.outputs.checkov_results }})" >> $GITHUB_ENV
+      
+      
+#       # - name: Upload SARIF File
+#       #   if: success()
+#       #   uses: actions/upload-artifact@v4
+#       #   with:
+#       #     name: results.sarif #checkov-sarif-results
+#       #     path: ${{ steps.checkov_scan.outputs.checkov_results }} #. #checkov_results.sarif
+#       #     # overwrite: false
+
+#       # - name: Save SARIF File as Artifact
+#       #   if: success()
+#       #   uses: actions/upload-artifact@v2
+#       #   with:
+#       #     name: checkov-sarif-results
+#       #     path: checkov_results.sarif
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+# # name: checkov
+
+# # # Controls when the workflow will run
+# # on:
+# #   # Triggers the workflow on push or pull request events but only for the "main" branch
+# #   # push:
+# #   #   branches: [ "main", "master" ]
+# #   # pull_request:
+# #   #   branches: [ "main", "master" ]
+
+# #   # Allows you to run this workflow manually from the Actions tab
+# #   workflow_dispatch:
+
+# # # A workflow run is made up of one or more jobs that can run sequentially or in parallel
+# # jobs:
+# #   # This workflow contains a single job called "scan"
+# #   scan:
+# #     permissions:
+# #       contents: read # for actions/checkout to fetch code
+# #       security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
+# #       actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
+      
+# #     # The type of runner that the job will run on
+# #     runs-on: ubuntu-latest
+
+# #     # Steps represent a sequence of tasks that will be executed as part of the job
+# #     steps:
+# #       # Checks-out your repository under $GITHUB_WORKSPACE, so follow-up steps can access it
+# #       - uses: actions/checkout@v4
+
+# #       - name: Checkov GitHub Action
+# #         uses: bridgecrewio/checkov-action@v12
+# #         with:
+# #           # This will add both a CLI output to the console and create a results.sarif file
+# #           output_format: cli,sarif
+# #           output_file_path: console,results.sarif
+        
+# #       - name: Upload SARIF file
+# #         uses: github/codeql-action/upload-sarif@v3
+        
+# #         # Results are generated only on a success or failure
+# #         # this is required since GitHub by default won't run the next step
+# #         # when the previous one has failed. Security checks that do not pass will 'fail'.
+# #         # An alternative is to add `continue-on-error: true` to the previous step
+# #         # Or 'soft_fail: true' to checkov.
+# #         if: success() || failure()
+# #         with:
+# #           sarif_file: results.sarif
